// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFl4iwIlinWZDkyTLsxE8Wo_7NZYKfzPE',
    appId: '1:45227864348:web:3826ee5094d066f1568ad9',
    messagingSenderId: '45227864348',
    projectId: 'baek-a5194',
    authDomain: 'baek-a5194.firebaseapp.com',
    storageBucket: 'baek-a5194.appspot.com',
    measurementId: 'G-X5BKKH97LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2nbK91bd0X-8saBDoVM0pxehOPsde2Mw',
    appId: '1:45227864348:android:373a915f76eb1b05568ad9',
    messagingSenderId: '45227864348',
    projectId: 'baek-a5194',
    storageBucket: 'baek-a5194.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQlIpQrZabUzuRx7gxntZdk9S9pNCXz7k',
    appId: '1:45227864348:ios:437524754bc28013568ad9',
    messagingSenderId: '45227864348',
    projectId: 'baek-a5194',
    storageBucket: 'baek-a5194.appspot.com',
    iosBundleId: 'com.example.baek1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQlIpQrZabUzuRx7gxntZdk9S9pNCXz7k',
    appId: '1:45227864348:ios:437524754bc28013568ad9',
    messagingSenderId: '45227864348',
    projectId: 'baek-a5194',
    storageBucket: 'baek-a5194.appspot.com',
    iosBundleId: 'com.example.baek1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFl4iwIlinWZDkyTLsxE8Wo_7NZYKfzPE',
    appId: '1:45227864348:web:a22fb74f5df291d6568ad9',
    messagingSenderId: '45227864348',
    projectId: 'baek-a5194',
    authDomain: 'baek-a5194.firebaseapp.com',
    storageBucket: 'baek-a5194.appspot.com',
    measurementId: 'G-XK6H0NH4G5',
  );
}
